name: Publish Runner Image by using Packer

on:
  push:
    branches:
      - main
    paths:
      - 'images/**'
      - '.github/workflows/packer-publish-image.yaml'
  pull_request:
    branches:
      - main
    paths:
      - 'images/**'
      - '.github/workflows/packer-publish-image.yaml'
permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository_owner }}/actions-runner
  PACKER_PRODUCT_VERSION: "1.8.6"
jobs:
  packer:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: ${{ env.PACKER_PRODUCT_VERSION }}

      - name: Run `packer init`
        id: init
        run: |
          packer init ./images/ubuntu/templates/docker-ubuntu-22.04.pkr.hcl

      - name: Run `packer validate`
        id: validate
        run: |
          packer validate ./images/ubuntu/templates/docker-ubuntu-22.04.pkr.hcl

      - name: Run `packer build`
        if: github.event_name == 'push'
        run: |
          packer build --var artifact_image_repository=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }} --var artifact_image_tag=ubuntu-${{github.run_number}} ./images/ubuntu/templates/docker-ubuntu-22.04.pkr.hcl 
